apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: html-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/subha-ui/sub.git
    targetRevision: main
    path: .
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
