apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ArgoCD Demo</title>
    </head>
    <body>
        <h1>Hello from ArgoCD ðŸš€</h1>
    </body>
    </html>