apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: nginx-deployment
=======
  name: python-hello
>>>>>>> 5c2126327313ae3e7bd4423f1cd465da31e3583f
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config
=======
      app: python-hello
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
      - name: python-hello
        image: python-hello:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

>>>>>>> 5c2126327313ae3e7bd4423f1cd465da31e3583f
